name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # ✅ 存在
      - uses: actions/configure-pages@v5 # ✅ 存在
      - uses: actions/upload-pages-artifact@v1 # ❌ 原来写 v4 是错误的
        with:
          path: . # 表示将仓库根目录作为 Pages 内容

      - uses: actions/deploy-pages@v1 # ✅ deploy-pages 确实是 v1
